# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.5.0

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install global packages
          command: sudo npm install -g truffle codecov

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Solidity Linter
          command: npm run lint:sol

      - run:
          name: Javascript Linter
          command: npm run lint:js

      - run:
          name: Tests without any coverage
          command: npm test

      # TODO: Enable code coverage when we have code to properly test.
      # - run:
      #     name: Unit tests with code coverage
      #     command: npm run test:cov
      #
      # - run:
      #     name: Send reports to codecov.io
      #     command: codecov